kcontacts: Autospec creation for update from version 5.115.0 to version 6.0.0
Alexander Lohnau (1):
      Remove code for generating pri file

Antonio Rojas (1):
      Clarify QtQuick dependency

Carl Schwan (2):
      Update api doc of CalendarUrl
      Add extra types to ResourceLocatorUrl

David Faure (1):
      Port to ECMFeatureSummary

Friedrich W. H. Kossebau (10):
      Bump KF disabled deprecation level to 5.240
      Mark private methods of public classes as unexported
      Set target properties right after declaring the target
      Generate version header on src/ level
      Have export macros header include version header
      Use all-upper-case version variable names (KF consistency)
      Include only needed headers instead of QtTest module header
      Add explicit moc includes to sources for moc-covered headers
      Drop unneeded Qt metatype declarations
      Adapt to KConfigGroup name officially being a QString type

Heiko Becker (1):
      GIT_SILENT Upgrade Qt6 version requirement to 6.5.0.

Jonathan Esk-Riddell (13):
      Update version number for 5.245.0
      Update version number for 5.245.0
      Update version number for 5.246.0
      Update version number for 5.247.0
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release

Julius Künzel (2):
      FIx non-void return
      FIx undefined reference to qMain(int, char**)

Laurent Montel (3):
      Use Q_RELOCATABLE_TYPE instead of deprecated Q_MOVABLE_TYPE
      GIT_SILENT: Remove mention of qmake library from metainfo.yaml
      GIT_SILENT: Port to new CI template

Luigi Toscano (1):
      Fix the translation template version number (5->6)

Nicolas Fella (7):
      Remove Qt5 CI
      Require Qt6
      Update KF_VERSION for KF6 development
      Rename CMake targets/config/libraries for KF6
      Bump KF_DEP_VERSION for KF6
      Drop more deprecated API
      Fix clang build

Volker Krause (9):
      Bump Qt deprecation level to 6.4
      Remove Qt 5 support
      Remove deprecated API
      Port away from QTextCodec
      Clean up AddresseeHelper now that it is an implementation detail
      Replace QVector by QList
      Replace QVariantList properties with their actual types
      Add Address::geoUri getter and property
      Port away from deprecated QDateTime API

l10n daemon script (56):
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours